quarkus.http.port=8081

kafka.bootstrap.servers=localhost:29092

mp.messaging.outgoing.order-created.connector=smallrye-kafka
mp.messaging.outgoing.order-created.topic=order-created
mp.messaging.outgoing.order-created.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
